-- INSERT INTO journals
-- (body, day_selection_id)
-- VALUES
-- ('Today was a great day!', 1),
-- ('This morning was rough, but things turned around in the afternoon', 2),
-- ('I am a little unsure about my new job', 3),
-- ('I feel really good in my skin', 4),
-- ('Today was ok - not good but not bad either', 5);